<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studentJson" nsURI="http://jsondiscoverer/discovered/studentJson"
    nsPrefix="composeds">
  <eClassifiers xsi:type="ecore:EClass" name="PackagedElement">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="PackagedElement" value="1"/>
        <details key="OwnedAttribute" value="1"/>
        <details key="Content" value="1"/>
        <details key="OwnedOperation" value="1"/>
        <details key="OwnedParameter" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="5"/>
      <details key="source" value="studentJson"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="id" value="5"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PackagedElement" value="1"/>
          <details key="OwnedAttribute" value="1"/>
          <details key="Content" value="1"/>
          <details key="OwnedOperation" value="1"/>
          <details key="OwnedParameter" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="5"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eClass" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="eClass" value="5"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PackagedElement" value="1"/>
          <details key="OwnedAttribute" value="1"/>
          <details key="Content" value="1"/>
          <details key="OwnedOperation" value="1"/>
          <details key="OwnedParameter" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="5"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="#//Data">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="data" value="5"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PackagedElement" value="1"/>
          <details key="OwnedAttribute" value="1"/>
          <details key="Content" value="1"/>
          <details key="OwnedOperation" value="1"/>
          <details key="OwnedParameter" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="5"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Data" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="studentJson"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="name" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Data" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="visibility" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Data" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="type" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Data" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAttribute" upperBound="-1"
        eType="#//PackagedElement">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="ownedAttribute" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Data" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameter" upperBound="-1"
        eType="#//PackagedElement">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="ownedParameter" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Data" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperation" upperBound="-1"
        eType="#//PackagedElement">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="ownedOperation" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Data" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packagedElement" lowerBound="1"
        upperBound="-1" eType="#//PackagedElement">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="packagedElement" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Data" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Json">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Json" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="studentJson"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="version" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Json" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="encoding" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Json" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="json" lowerBound="1" eType="#//Json">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="json" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Json" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ns" lowerBound="1" eType="#//N">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="ns" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Json" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        upperBound="-1" eType="#//PackagedElement">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="content" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Json" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="N">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="N" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="studentJson"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uml" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="uml" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="N" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
